"use client";
import { useEffect, useState } from "react";
import { usePathname } from "next/navigation";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./header";
import Footer from "./footer";
import { AnimatePresence, motion } from "framer-motion";
import { AuthProvider } from "./context/authContext";

const roboto = Roboto({
  subsets: ['latin'], // required
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], // optional: choose the weights you need
  style: ['normal', 'italic'], // optional
  display: 'swap', // improves performance
})



// export const metadata = {
//   title: "Create Next App Design",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const pathname = usePathname();

  // Hide footer on these routes
  const noFooterRoutes = ["/login", "/register", "/account-details", "/memberships", "/class-history"];
  const hideFooter = noFooterRoutes.includes(pathname);

  console.log("Path : ", hideFooter);
  

  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        
            <Header />
            <AuthProvider>{children}</AuthProvider>
            {!hideFooter && <Footer />} 
        
      </body>
    </html>
  );
}
